sprint_3/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    # Основной шаблон 
    path('b1/', views.index_1),
    # Дополнительный шаблон 
    path('b2/', views.index_2),
    # Главная страница после создания моделей
    path('', views.poems, name='poems'),
    path('poems/<str:web_name>/', views.poem_author, name='author'),
    path('poem/<int:argument_id>/', views.post_detail, name='poem'),
    path('users/<str:user_name>/', views.poem_user, name='name_user'),
    path('biorafy/<str:name>/', views.biografy, name='biografy'),
    path('default/', views.default),

]

sprint_3/sprint_3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]

sprint_3/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Biografy(models.Model):
    name = models.CharField('Автор', max_length=100)
    birthday = models.DateField('Дата рождения', null=True, blank=True)
    date_of_death = models.DateField('Дата смерти', null=True, blank=True)
    text = models.TextField('Имформация о жизни')

    def __str__(self): 
        return self.name


class Author(models.Model):
    first_name = models.CharField('Имя Автора', max_length=100)
    last_name = models.CharField('Фамилия Автора', max_length=100)
    name_url = models.CharField(verbose_name='Страница автора', max_length=30, unique=True)
    description = models.OneToOneField(
        Biografy,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='bio',
        verbose_name='Справка о писателе')

    def __str__(self): 
        return f'{self.first_name} {self.last_name}'


class Poem(models.Model):
    text = models.TextField(verbose_name='Стихи')
    author = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name='poems',
        verbose_name='Автор'
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата добавления', auto_now_add=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='poems',
        verbose_name='Любитель поэзии'
    )

    class Meta:
        verbose_name = 'Произведение' 
        verbose_name_plural = 'Произведения' 

 
    def __str__(self): 
        return self.text[:40] 

sprint_3/posts/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse

from .models import Author, Biografy, Poem, User


def default(request):
    return HttpResponse(
        '<h1>Разработчик пока непридумал, что будет по этому адресу, '
        'поэтому просто вывел это сообщение</h1>'
    )

def index_1(request):    
    return render(request, 'posts/index_1.html')

def index_2(request):    
    return render(request, 'posts/index_2.html')


def poems(request):
    poems = Poem.objects.all()
    context = {
       'poems': poems,
    }
    return render(request, 'posts/poems.html', context)

def poem_author(request, web_name):
    author = get_object_or_404(Author, name_url=web_name)
    poems = author.poems.all()  # .first()
    context = {
        'author': author,
        'poems': poems,
    }
    return render(request, 'posts/poem_author.html', context)

def post_detail(request, argument_id):
    poem = get_object_or_404(Poem, pk=argument_id)
    context = {
        'poem': poem,
    }
    return render(request, 'posts/poem_detail.html', context)

def poem_user(request, user_name):
    user = get_object_or_404(User, username=user_name)
    poems = user.poems.all()  # .first()
    context = {
        'user': user,
        'poemsis': poems,
    }
    return render(request, 'posts/poem_user.html', context)

def biografy(request, name):
    biografy = get_object_or_404(Biografy, name=name)
    poem_last = biografy.bio.poems.last()
    # poem_last = Author.objects.get(id=biografy.bio.id).poems.last()
    context = {
        'user': biografy,
        'poem': poem_last,
    }
    return render(request, 'posts/biografy.html', context)

sprint_3/templates/base1.html
<html>
  <head>
    {% include 'includes/head.html' %}
    <title>{% block title %}Поэзия{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header_1.html' %}
    <main> 
      <div class="container py-5">     
        <h1>Поэзия, которую знают все.</h1>
        {% block post_1 %}
        {% endblock %}
        {% block post_2 %}
        {% endblock %}
        {% block post_3 %}
        {% endblock %}
        <hr>
      </div>  
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

sprint_3/templates/base2.html
<html>
  <head>
    {% include 'includes/head.html' %}
    <title>{% block title %}Поэзия 21 века{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header_2.html' %}
    <main> 
      <div class="container py-5">     
        {% block author %}<h1>Стихи современников</h1>{% endblock %} 
        {% block post_1 %}
          <p>В базе пока нет стихой современников.</p>
        {% endblock %}
      </div>  
    </main>
    {% include 'includes/footer.html' %}
  </body>
</html>

sprint_3/templates/base_base.html
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Последние обновления на сайте</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">        
        <!-- все посты перебираются в цикле -->
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
              <a href="../posts/profile.html">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: 31 июля 1854 
            </li>
          </ul>
          <p>
            [Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. 
            Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] 
            по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. 
            Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] 
            день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ 
            служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся 
            такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше. 
          </p>
          <a href="../posts/post_detail.html">подробная информация</a>
        </article>       
        <a href="../posts/group_list.html">все записи группы</a>        
        <hr>
        <article>
          <ul>
            <li>
              Автор: Лев Толстой
              <a href="../posts/profile.html">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: 30 июля 1854 
            </li>
          </ul>
          <p>
            Рымник.] Сдѣлалъ верхомъ переходъ до Рымника. [[5]] Старикъ все не кланяется 
            мнѣ. Обѣ вещи эти злятъ меня. Съ встрѣчавшимися баши-бузуками велъ себя хорошо. 
            Объяснился съ Крыжановскимъ. Онъ, не знаю зачѣмъ, совѣтуетъ мнѣ 
            прикомандироваться къ казачьей батареѣ; совѣтъ, которому я не послѣдую. 
            Желчно спорилъ вечеромъ съ Фриде и Бабарыкинымъ, ругалъ Сержпутовскому и 
            ничего не сдѣлалъ, вотъ 3 упрека, которыя дѣлаю себѣ за нынѣшній день. (3)
          </p>
          <a href="../posts/post_detail.html">подробная информация</a>
        </article>       
        <a href="../posts/group_list.html">все записи группы</a>    
        <!-- нет черты после последнего поста -->
        <!-- если записей больше 10 -- подключён паджинатор -->
        <nav class="my-5">
          <ul class="pagination">    
            <li class="page-item">
              <a class="page-link" href="#0">Первая</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#0">Предыдущая</a>
            </li>
            <li class="page-item active">
              <span class="page-link">1</span>
            </li>
            <li class="page-item">
              <a class="page-link" href="#0">2</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#0">3</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#0">Следующая</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="#0">Последняя</a>
            </li>
          </ul>
        </nav>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

sprint_3/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2021 Copyright <span style="color:red">Поэзия</span></p>    
</footer>

sprint_3/templates/includes/head.html
{% load static %} 
<meta charset="utf-8"> <!-- Кодировка сайта -->
<!-- Сайт готов работать с мобильными устройствами -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Загружаем фав-иконки -->
<link rel="icon" href="img/fav/fav.ico" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href=""> 
<meta name="msapplication-TileColor" content="#000">
<meta name="theme-color" content="#ffffff">
<!-- Подключен файл со стандартными стилями бустрап -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

sprint_3/templates/includes/header_1.html
<header>
  <nav class="navbar navbar-light" style="background-color: LightCoral">
    <div class="container">
      <a class="navbar-brand" href="index.html"> 
        {% comment %} {% url 'posts:poems' %} {% endcomment %}
        <img src="image/image.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:blue">Поэзия</span></a>
    </div>
  </nav>      
</header>

sprint_3/templates/includes/header_2.html
<header>
  <nav class="navbar navbar-light" style="background-color: PapayaWhip">
    <div class="container" style="height: 200">
      <a class="navbar-brand" href="index.html">
        <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <h1><span style="color: black">Поэзия</span></h1></a>
        <h1>Для некоторых страниц нужен другой дизайн</h1>
    </div>
  </nav>      
</header>

sprint_3/templates/includes/header_3.html
<header>
  <nav class="navbar navbar-light" style="background-color: PapayaWhip">
    <div class="container" style="height: 200">
      <a class="navbar-brand" href="{% url 'posts:poems' %}">
        <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <h1><span style="color: black">Поэзия</span></h1></a>
      <h1>Для некоторых страниц нужен другой дизайн</h1>
    </div>
  </nav>      
</header>

sprint_3/templates/posts/biografy.html
{% extends 'base1.html' %}

{% comment %} {% block title %}биография {{ poem.author.first_name }} {{ poem.author.last_name }}{% endblock %} {% endcomment %}

{% block author %} 
  {% comment %} <h3><a href="{% url 'posts:author' poem.author.name_url %}">{{ poem.author.first_name }} {{ poem.author.last_name }}</a></h3> {% endcomment %}
  <p>Краткая биография автора: {{ user.text | linebreaksbr }}</p>
{% endblock %}
{% block post_1 %}
<h3>{{ user.bio.first_name }} {{ user.bio.last_name }}</h3>

<p>Родился: {{ user.birthday }}</p>
<p>Перестал творить: {{ user.date_of_death }}</p>
<p>Краткая биография автора: {{ user.text | linebreaksbr }}</p>
<hr>
<h4>Последнее добавленное произведение автора на сайт:</h4>
<p>{{ poem.text | linebreaksbr | truncatewords:15 }}</p>
<a href="{% url 'posts:poem' poem.id %}">Прочитать</a>
{% endblock %}

sprint_3/templates/posts/index_1.html
{% extends 'base1.html' %}
{% comment %} При подключении базового шаблона, переданные блоки найдут
свои места в базовом шаблоне по имени и отобразятся там где для них
установлена закладка {% endcomment %}
<p>hdhdhsdhshshhshshsdhsd</p>
{% block post_2 %}
  {% include 'posts/poems/poem2.html' %}
{% endblock %}

{% block post_3 %}
  {% include 'posts/poems/poem3.html' %}
{% endblock %}

{% block post_1 %}
  {% include 'posts/poems/poem1.html' %}
{% endblock %}





{% block title %}Когда-то написал Есенин{% endblock %}

sprint_3/templates/posts/index_2.html
{% extends 'base2.html' %}

{% block post_1 %}

{% endblock %}

sprint_3/templates/posts/poem_author.html
{% extends 'base2.html' %}

{% block title %}Стихи {{ author.first_name }} {{ author.last_name }}{% endblock %}

{% block author %} 
  <h1>{{ author.first_name }} {{ author.last_name }}</h1>
  {% if author.description %}
  <p><a href="{% url 'posts:biografy' author.description.name %}">Краткая биография автора:</a> {{ author.description.text | linebreaksbr | truncatewords:8 }}</p>
  {% endif %}
{% endblock %}
{% block post_1 %}
{% for poem in poems %}
  <p>Добавил: <a href="{% url 'posts:name_user' poem.user.username %}">
    {{ poem.user.first_name }} {{ poem.user.last_name }}</a></p>
  <p>{{ poem.text | linebreaksbr | truncatewords:8 }}</p>
  <a href="{% url 'posts:poem' poem.pk %}">Прочитать</a>
  <hr>
{% endfor %} 
{% endblock %}

sprint_3/templates/posts/poem_detail.html
{% extends 'base2.html' %}

{% block title %}Произведение {{ poem.author.first_name }} {{ poem.author.last_name }}{% endblock %}

{% block author %} 
  <h3><a href="{% url 'posts:author' poem.author.name_url %}">{{ poem.author.first_name }} {{ poem.author.last_name }}</a></h3>
  {% if poem.author.description %}
    <p><a href="{% url 'posts:biografy' poem.author.description.name %}">Краткая биография автора:</a> {{ poem.author.description.text | linebreaksbr | truncatewords:8 }}</p>
  {% endif %}
{% endblock %}
{% block post_1 %}
  <p>Добавил: <a href="{% url 'posts:name_user' poem.user.username %}">{{ poem.user.first_name }} {{ poem.user.last_name }}</a></p>
  {{ poem.text | linebreaksbr }}
{% endblock %}

sprint_3/templates/posts/poem_user.html
{% extends 'base2.html' %}

{% block title %}Любитель {{ user.first_name }} {{ user.last_name }} {% endblock %}

{% block author %} <h3>Добавил: {{ user.first_name }} {{ user.last_name }}</h3> {% endblock %}
{% block post_1 %}
{% for poem in poemsis %}
  <a href="{% url 'posts:author' poem.author.name_url %}">
    <h4>{{ poem.author.first_name }} {{ poem.author.last_name }}</h4>
  </a>
  {{ poem.text | linebreaksbr | truncatewords:8 }}
  <p><a href="{% url 'posts:poem' poem.pk %}">Прочитать</a></p>
  <hr>
{% endfor %} 
{% endblock %}

sprint_3/templates/posts/poems.html
{% extends 'base1.html' %}

{% block title %}Произведения{% endblock %}

{% block post_1 %}
{% for poem in poems %}
  <a href="{% url 'posts:author' poem.author.name_url %}">
    <h3>{{ poem.author.first_name }} {{ poem.author.last_name }}</h3>
  </a>
  <p>Добавил: <a href="{% url 'posts:name_user' poem.user.username %}">{{ poem.user.first_name }} {{ poem.user.last_name }} </a></p>
  <p>{{ poem.text | linebreaksbr | truncatewords:8 }}</p>
  <a href="{% url 'posts:poem' poem.pk %}">Прочитать</a>
  <hr>
{% endfor %} 
{% endblock %}

sprint_3/templates/posts/poems/poem1.html
<article>
  <p>
    Да Теперь - решено без возврата<br>
    Я покинул родные края<br>
    Уж не будут листвою крылатой<br>
    Надо мною звенеть тополя.
  </p>    
</article>

sprint_3/templates/posts/poems/poem2.html
<article>
  <p>
    Низкий дом мой давно уж ссутулился<br>
    Старый пес мой давно издох.<br>
    На московских изогнутых улицах<br>
    Помереть знать судил мне бог
  </p>
</article>

sprint_3/templates/posts/poems/poem3.html
<article>
    <p>
      Я люблю этот город вязевый<br>
      Пусть обрюзг он и пусть одрях<br>
      Золотая дремотная Азия<br>
      Опочила на куполах<br>
      А когда ночью светит месяц,<br>
      Когда светит... черт знает как<br>
      Я иду, головою свесясь,<br>
      Переулком в знакомый кабак 
    </p>
</article>